name: pnChat
version: '${version}'
main: ru.privatenull.pnChatPlugin
api-version: '1.21'
authors: [privatenull]
softdepend: [Essentials, LiteBans, AdvancedBan, CMI, LuckPerms, PlaceholderAPI]
commands:
  pnchat:
    description: Управление pnChat
    usage: /pnchat reload
    permission: pnchat.admin
permissions:
  pnchat.admin:
    default: op
