name: pnChat
version: '${version}'
main: ru.privatenull.pnChatPlugin
api-version: '1.21'
authors: [privatenull]
softdepend: [Essentials, LiteBans, AdvancedBan, CMI, LuckPerms, PlaceholderAPI]
commands:
  pnchat:
    description: Управление pnChat
    usage: /pnchat reload
    permission: pnchat.admin
  chatcolor:
    description: Устанавливает цвет чата игрока
    usage: /chatcolor <цвет|none> <ник>
    permission: pnchat.chatcolor
  chatfont:
    description: Устанавливает стиль чата игрока
    usage: /chatfont <шрифт...|none> <ник>
    permission: pnchat.chatfont
permissions:
  pnchat.admin:
    default: op
  pnchat.chatcolor:
    default: op
  pnchat.chatfont:
    default: op
